services:
  tensorflow:
    image: tensorflow:2.10.1-gpu
    build:
      context: ..
      dockerfile: tensorflow-2.10.1-gpu.Dockerfile
      args:
        USERNAME: kstef
        USER_ID: 1003
        GROUP_ID: 1003
      tags:
        - "tensorflow:2.10.1-gpu"
    container_name: tf-gpu
    hostname: tensorflow-container-gpu
    user: kstef
    tty: true
    stdin_open: true
    working_dir: /mnt/
    volumes:
      - /home/kstef/Semantic-Segmentation:/mnt/Semantic-Segmentation
      - /home/kstef/.keras:/mnt/.keras
      - /home/kstef/dataset:/mnt/dataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]